// Regression scenarios use synthetic commercial data; no production records.
const core=require('../src/core'),fs=require('fs');
let ok=0,bad=0;
const T=(n,c)=>{c?ok++:bad++;console.log((c?'  ok  ':'  FALHA ')+n)};
const carga=(cliente,sigla,toneladas,net)=>({cliente,sigla,toneladas,net,proprio:core.ehGrupoJBS(cliente)});
const r=[carga('Flora GO','AAA',120,4500.123456789),carga('Cliente A','AAA',30,5000),
 carga('Cliente B','AAA',90,5400),carga('Flora SP','BBB',80,5200),carga('JBS Industrial','AAA',20,2000)];
const o=[carga('Flora GO','AAA',60,4500.123456789)];
const refs=core.aplicarReferenciasProgramadas(r,o),ag=core.agregarSemana(r,o,[]);
const go=ag.porPropria.find(p=>p.cliente==='Flora GO'),sp=ag.porPropria.find(p=>p.cliente==='Flora SP');
T('weighted programmed reference, not simple mean',Math.abs(r[0].netTerMed-5300)<1e-9);
T('independent client count excludes all JBS',r[0].nTer===2);
T('best programmed third party and its identity agree',r[0].netTer===5400&&r[0].clienteTer==='Cliente B');
T('minimum and maximum use programmed destinations',r[0].netTerMin===5000&&r[0].netTerMax===5400);
T('actual deviation has negative sign',Math.abs(go.saving_realizado-(4500.123456789-5300)*120)<1e-7);
T('model uses actual programmed reference',o[0].netTerMed===5300);
T('model deviation remains separate',go.ton_otimo===60&&go.ton_realizado===120);
T('different volume bases cannot justify a performance badge',!core.basesComparaveis(r,o,'Flora GO'));
T('missing reference remains null',sp.saving_realizado===null&&sp.ton_comp_realizado===0);
T('uncomparable volume remains in total',sp.ton_realizado===80);
T('missing origin is identified',sp.origens_sem_comp_realizado.join()==='BBB');
T('JBS named without BioPower remains internal',core.ehPropriaFabrica('JBS Industrial'));
T('independent name with JBS inside another word remains external',!core.ehGrupoJBS('AJBSX'));
const m=core.memoriaPorOrigem(r,'Flora GO',refs);
T('memory totals reproduce aggregate without intermediate rounding',Math.abs(m.reduce((s,x)=>s+(x.impacto||0),0)-go.saving_realizado)<1e-7);
T('memory contains third party programmed volumes',m[0].terceiros.reduce((s,x)=>s+x.toneladas,0)===120);
T('memory exposes per-ton difference',Math.abs(m[0].diferencaPorTonelada-(4500.123456789-5300))<1e-9);
T('memory isolates unmatched volume',core.memoriaPorOrigem(r,'Flora SP',refs)[0].toneladasSemReferencia===80);
const zero=core.agregarSemana(r,[],[]).porPropria.find(p=>p.cliente==='Flora GO');
T('zero model volume has no economic result',zero.ton_otimo===0&&zero.saving_otimo===null);
const partial=[carga('Flora GO','AAA',10,5500),carga('Flora GO','BBB',20,6000),carga('Cliente A','AAA',5,5000)];
core.aplicarReferenciasProgramadas(partial,[]);
const pg=core.agregarSemana(partial,[],[]).porPropria[0];
T('partial reference compares only covered volume',pg.ton_realizado===30&&pg.ton_comp_realizado===10);
T('positive difference uses comparable volume',pg.saving_realizado===5000);
T('partial memory reproduces result',core.memoriaPorOrigem(partial,'Flora GO')[0].impacto===5000);
const invalid=[carga('Flora GO','AAA',10,6000),carga('Cliente A','AAA',10,5000),carga('Cliente B','AAA',20,null)];
core.aplicarReferenciasProgramadas(invalid,[]);
T('missing NET among programmed parties invalidates incomplete benchmark',invalid[0].netTerMed===null);
T('invalid benchmark states the cause',/NET ausente/.test(invalid[0].motivoSemReferencia));
const unknown=[carga('Flora GO',null,10,6000),carga('Cliente A',null,10,5000)];
core.aplicarReferenciasProgramadas(unknown,[]);
T('unknown origins never join each other as benchmark',unknown[0].netTerMed===null);
T('unknown origin reason is explicit',/não identificada/.test(unknown[0].motivoSemReferencia));
const same=[carga('Flora GO','AAA',120,4000)];
T('same per-origin volumes are identifiable',core.basesComparaveis(r,same,'Flora GO'));
T('same total tons in another origin are not comparable',!core.basesComparaveis(r,[carga('Flora GO','ZZZ',120,4000)],'Flora GO'));
const semNet=[carga('Flora GO','AAA',10,null),carga('Cliente A','AAA',20,5000)];
core.aplicarReferenciasProgramadas(semNet,[]);
const semNetAg=core.agregarSemana(semNet,[],[]).porPropria[0];
T('missing plant NET cannot create negative economic deviation',semNetAg.saving_realizado===null);
T('missing plant NET cannot appear as zero average',semNetAg.net_realizado===null);
T('missing plant NET reason is explicit',/NET da planta/.test(semNet[0].motivoSemReferencia));
T('missing plant NET stays null in audit detail',core.memoriaPorOrigem(semNet,'Flora GO')[0].net===null);
const dbSource=fs.readFileSync(require.resolve('../db'),'utf8');
const startup=dbSource.slice(dbSource.indexOf('async function iniciar()'),dbSource.indexOf('async function corrigirFlagPropria()'));
T('startup no longer rewrites economic historical rows',!startup.includes('await migrarNetTerMedio()')&&!startup.includes('await corrigirFlagPropria()'));
T('new close recalculates references on server',dbSource.includes('core.aplicarReferenciasProgramadas(linhas, cab.linhasOtimo)'));
T('close rejects undefined economic data',dbSource.includes('Carga sem cliente, origem, volume positivo ou NET válido.'));
T('concurrent closing serializes versions',dbSource.includes('pg_advisory_xact_lock'));
T('NET persistence retains financial precision',dbSource.includes('TYPE NUMERIC(18,9)'));
T('consolidated memory uses shared calculation',dbSource.includes('core.memoriaPorOrigem'));
T('monthly memory selects shipments after weekly reference construction',dbSource.includes('AS em_periodo')&&dbSource.includes('a.emPeriodo'));
T('history reports uncomparable volumes',dbSource.includes('AS volume_sem_referencia'));
const ui=fs.readFileSync(__dirname+'/../src/ui.js','utf8');
T('Home does not confuse absent reference with economic zero',ui.includes("temSavR ? rs(savR) : 'Não apurado'"));
T('Home identifies the plant on the calculation disclosure',ui.includes("Ver composição da diferença · "));
T('manual choice impact is identified as theoretical',ui.includes('não é perda realizada nem alternativa validada'));
T('Home explicitly differentiates programming and shipments',ui.includes('A programação não confirma embarques realizados'));
const cons=fs.readFileSync(__dirname+'/../public/consolidado.html','utf8');
T('history leaves unknown points unmeasured',cons.includes('if(p.valor==null)'));
T('consolidated summary preserves null result',cons.includes("temSavR ? rs(savR) : 'Não apurado'"));
T('consolidated detail shows reference by week and origin',cons.includes('p.memoria_realizado'));
console.log('\n'+ok+' OK, '+bad+' falhas');process.exit(bad?1:0);
